elasticsearch:
  image: elasticsearch
  volumes:
    - /data/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
logstash:
  image: logstash
  command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
